# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: battle_rep.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62\x61ttle_rep.proto\"\x87\x01\n\x04main\x12\x0e\n\x06gameID\x18\x02 \x01(\x05\x12(\n\x0eplayer_results\x18\x08 \x01(\x0b\x32\x10.personal_result\x12\x1a\n\x07players\x18\xc9\x01 \x03(\x0b\x32\x08.players\x12)\n\x0eplayers_result\x18\xad\x02 \x03(\x0b\x32\x10.players_results\"E\n\x0fplayers_results\x12\x0f\n\x07some_id\x18\x01 \x01(\x05\x12!\n\x07results\x18\x02 \x01(\x0b\x32\x10.personal_result\"?\n\x07players\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12!\n\rname_and_clan\x18\x02 \x01(\x0b\x32\n.name_clan\"\'\n\tname_clan\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63lan\x18\x05 \x01(\t\"\xfe\x01\n\x0fpersonal_result\x12\x0e\n\x06\x64\x61mage\x18\x08 \x01(\x05\x12\r\n\x05shots\x18\x04 \x01(\x05\x12\n\n\x02xp\x18\x03 \x01(\x05\x12\x0c\n\x04hits\x18\x05 \x01(\x05\x12\x14\n\x0cpenetrations\x18\x07 \x01(\x05\x12\x11\n\tplayer_id\x18\x65 \x01(\x05\x12\x0e\n\x06\x61ssist\x18\t \x01(\x05\x12\x14\n\x0chit_received\x18\x0c \x01(\x05\x12\x15\n\rpens_received\x18\x0f \x01(\x05\x12\x18\n\x10non_pen_received\x18\r \x01(\x05\x12\x17\n\x0f\x64\x61maged_enemies\x18\x11 \x01(\x05\x12\x19\n\x11\x64\x61maged_destroyed\x18\x12 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'battle_rep_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAIN._serialized_start=21
  _MAIN._serialized_end=156
  _PLAYERS_RESULTS._serialized_start=158
  _PLAYERS_RESULTS._serialized_end=227
  _PLAYERS._serialized_start=229
  _PLAYERS._serialized_end=292
  _NAME_CLAN._serialized_start=294
  _NAME_CLAN._serialized_end=333
  _PERSONAL_RESULT._serialized_start=336
  _PERSONAL_RESULT._serialized_end=590
# @@protoc_insertion_point(module_scope)
